Feature/movie app
StudyFork/CleanArchitectureStudy02 pull request #20
Opened 2020-02-28 09:58 UTC by dlwls5201

toy project using coroutine

2020-03-15 14:37 UTC, zion830 requested changes
안녕하세요~ 리뷰 남겨봤습니다 !
깔끔하게 잘 짜두셔서 보면서 저도 참고가 많이 되었습니다 ㅎㅎ

2020-03-15 14:37 UTC, zion830 commented on ToyProject/app/src/main/java/com/example/movieapplication/data/repository/MovieRepositoryImpl.kt
> +    override suspend fun get(page: Int): MovieResponse {
메서드 명이 get()으로 되어있어서 처음 봤을 때 이 클래스의 인스턴스(MovieRepositoryImpl)가 반환되는 함수인가..? 라는 생각이 들었습니다. 어떤 값을 반환하는지 붙여주면 좋을 것 같습니다!

2020-03-15 14:37 UTC, zion830 commented on ToyProject/app/src/main/java/com/example/movieapplication/data/source/remote/MovieApi.kt
> +        @Query("api_key") apiKey: String,
apikey처럼 모든 request에 일관되게 들어가는 쿼리스트링은 Interceptor로 처리해주면 좋을 것 같습니다!

2020-03-15 14:37 UTC, zion830 commented on ToyProject/app/src/main/java/com/example/movieapplication/base/BaseFragment.kt
> +abstract class BaseFragment<B : ViewDataBinding>(private val layoutId: Int) : Fragment() {
리소스 아이디엔 @LayoutRes 같은 어노테이션을 붙여주면 실수 방지 차원에서 유용할 것 같습니다 ㅎㅎ

2020-03-15 14:37 UTC, zion830 commented on ToyProject/app/src/main/java/com/example/movieapplication/base/BaseViewHolder.kt
> +abstract class BaseViewHolder<out B : ViewDataBinding, in D>(parent: ViewGroup, @LayoutRes layoutRes: Int) :
D의 super type이 명시되어 있지 않은데 혹시 in이 붙은 이유를 알 수 있을까요 ?

2020-03-15 14:37 UTC, zion830 commented on ToyProject/app/src/main/java/com/example/movieapplication/base/BaseViewModel.kt
> +    protected val uiDispatchers = Dispatchers.Main
Dispatchers.Main과 Dispatchers.IO는 이미 static 변수로 선언되어 있는데 여기에 다시 할당해두신 이유가 궁금해요~
변수 가독성 때문인가요?

2020-03-15 14:37 UTC, zion830 commented on ToyProject/app/src/main/java/com/example/movieapplication/bindingdapter/BindingAdapter.kt
> +    if (url != null) {
이 경우 url이 null일 때 imageView 부분이 아예 비게 될거 같은데요.
이 load() 함수의 원형이 `public RequestBuilder<Drawable> load(@Nullable String string)`라 null이 들어가더라도 내부적으로 처리가 될 것 같아요. 
null로 분기를 치는 대신 error() 메서드로 이미지가 로딩되지 않을 때의 리소스를 설정하면 어떨까 하는 생각입니다!

2020-03-15 14:37 UTC, zion830 commented on ToyProject/app/src/main/java/com/example/movieapplication/presenter/MainViewModel.kt
> +                delay(2000)
2초 대기가 들어간 이유가 궁금합니다~

2020-03-15 14:37 UTC, zion830 commented on ToyProject/app/src/main/java/com/example/movieapplication/presenter/MainViewModel.kt
> +            page++
response에 totalResult(전체 페이지 개수)도 들어가 있어서,
저 값을 활용해 가장 마지막 페이지에 도달했을 땐 addMovie를 하지 않는 처리까지 들어가면 좋을거 같네요ㅎㅎ

2020-03-15 14:37 UTC, zion830 commented on ToyProject/app/src/main/java/com/example/movieapplication/presenter/MovieAdapter.kt
> +                        itemView.setOnClickListener {
`itemView.setOnClickListener {
...
}`
이게 중첩되어 있어서 itemView에 리스너가 이중으로 set 되네요. 하나는 삭제해야 할거 같아요.

2020-03-15 14:37 UTC, zion830 commented on ToyProject/app/src/main/java/com/example/movieapplication/presenter/itemdecoration/MovieItemDecoration.kt
> +            outRect.bottom = 10
반복 사용되는 리터럴 값은 상수로 빼놓으면 수정에 대응하기 편해질것 같아요

2020-03-15 14:37 UTC, zion830 commented on ToyProject/app/src/main/java/com/example/movieapplication/presenter/MainActivity.kt
> +                            MovieAdapter.ViewType.LOADING -> 2
ViewType이 MovieAdapter 전용으로 사용되는 타입이라면, span count를 아예 enum 클래스 안에 프로퍼티로 넣어놓는건 어떤가요? 그럼 여기서 when을 사용할 필요가 없어 코드가 더 간결해질거 같아요
```
enum class ViewType(val spanCount: Int) {
    ITEM(1), LODING(2)
}
```

2020-03-16 10:15 UTC, dlwls5201 commented on ToyProject/app/src/main/java/com/example/movieapplication/data/repository/MovieRepositoryImpl.kt
> +    override suspend fun get(page: Int): MovieResponse {
class 이름에 Movie가 들어가니깐 get()만 하면 Movie를 받아오는 걸로 하면 어떨까 생각해 봤는데 좀더 명확하게 하는게 더 좋을것 같네요! 감사합니다.

24840f2

2020-03-16 10:15 UTC, dlwls5201 commented on ToyProject/app/src/main/java/com/example/movieapplication/data/source/remote/MovieApi.kt
> +        @Query("api_key") apiKey: String,
추가했습니다 :)

0904bf1

2020-03-16 10:16 UTC, dlwls5201 commented on ToyProject/app/src/main/java/com/example/movieapplication/base/BaseFragment.kt
> +abstract class BaseFragment<B : ViewDataBinding>(private val layoutId: Int) : Fragment() {
@DimenRes도 추가했습니다.

bf9173d

2020-03-16 10:17 UTC, dlwls5201 commented on ToyProject/app/src/main/java/com/example/movieapplication/base/BaseViewModel.kt
> +    protected val uiDispatchers = Dispatchers.Main
현재 어디에 선언해서 가져오면 좋을지 계속 고민하고 있는 단계입니다

2020-03-16 10:17 UTC, dlwls5201 commented on ToyProject/app/src/main/java/com/example/movieapplication/presenter/MainViewModel.kt
> +                delay(2000)
이건 테스트할려고 추가한건데 삭제했습니다 ㅎㅎ

2020-03-16 10:17 UTC, dlwls5201 commented on ToyProject/app/src/main/java/com/example/movieapplication/presenter/MainViewModel.kt
> +            page++
완료!

d7ff689

2020-03-16 10:18 UTC, dlwls5201 commented on ToyProject/app/src/main/java/com/example/movieapplication/presenter/MovieAdapter.kt
> +                        itemView.setOnClickListener {
세심한 부분까지..저도 신경을 못썻네요. 삭제했습니다.

ecc95ef

2020-03-16 10:18 UTC, dlwls5201 commented on ToyProject/app/src/main/java/com/example/movieapplication/presenter/MainActivity.kt
> +                            MovieAdapter.ViewType.LOADING -> 2
정말 좋은 생각인것 같습니다.

70bba8e

2020-03-16 10:19 UTC, dlwls5201 commented on ToyProject/app/src/main/java/com/example/movieapplication/presenter/itemdecoration/MovieItemDecoration.kt
> +            outRect.bottom = 10
dimens 값으로 변경

2020-03-16 10:19 UTC, dlwls5201 commented on ToyProject/app/src/main/java/com/example/movieapplication/bindingdapter/BindingAdapter.kt
> +    if (url != null) {
굳이 null 예외 처리 해주는 것보다 error를 해주는게 더 좋겠네요. 감사합니다.

dc6d67c

2020-03-16 10:24 UTC, dlwls5201 commented on ToyProject/app/src/main/java/com/example/movieapplication/base/BaseViewHolder.kt
> +abstract class BaseViewHolder<out B : ViewDataBinding, in D>(parent: ViewGroup, @LayoutRes layoutRes: Int) :
반공변성을 표현할 수도 있으나 저는 in 위치 (함수의 인자)에만 쓰도록 하기 위해서 추가했습니다.

**kotlin in action chapter9 제네릭스 중..**
`in이라는 키워드는 그 키워드가 붙은 타입이 이 클래스의 메소드 안으로 전달돼 메소드에 의해 소비된다는 뜻이다. 공변성의 경우와 마찬가지로 타입 파라미터의 사용을 제한함으로써 특정 하위 타입 관계에 도달할 수 있다. in 키워드를 타입 인자에 붙이면 그 타입 인자를 오직 인 위치에서만 사용할 수 있다는 뜻이다.`

2020-03-16 10:29 UTC, dlwls5201 reviewed
@zion830  
Coroutine과 Navigation을 이번 스터디 때 처음 사용해보는거라 리뷰 해주신 것에서 코드가 많이 변경되었습니다. :(
이점 양해 부탁드립니다. 리뷰 감사합니다.

2020-03-16 14:37 UTC, zion830 approved these changes
리뷰 반영된 부분 확인했습니다 👍🏼
수고하셨어요!

2020-04-05 03:54 UTC, merged