영화 목록 출력 PR작성
StudyFork/CleanArchitectureStudy02 pull request #21
Opened 2020-03-08 09:04 UTC by ironelder

영화 목록 출력 PR작성

2020-03-09 03:58 UTC, Nanamare commented
Confilcts 해결이 필요할 것 같습니다

2020-03-09 04:25 UTC, ironelder commented
> Confilcts 해결이 필요할 것 같습니다

confilcts제거 하였습니당 ㅠㅠ

2020-03-10 11:06 UTC, Nanamare requested changes

2020-03-10 11:06 UTC, Nanamare commented on ToyApplication/app/src/main/java/com/ironelder/toyapplication/MovieListFragment.kt
> +                return 2
GridLayoutManager(context, 3)
getSpanSize = 1 과 다른점이 있나요?

2020-03-10 11:06 UTC, Nanamare commented on ToyApplication/app/src/main/java/com/ironelder/toyapplication/MovieListFragment.kt
> +    fun getMovieList() {
기본으로 suspend 함수로 취급되지만
private suspend 를 추가하면 좀더 가독성 좋은시그니처를 가질 것 같습니다

2020-03-10 11:06 UTC, Nanamare commented on ToyApplication/app/src/main/java/com/ironelder/toyapplication/MovieListFragment.kt
> +                        (rv_movie_list.adapter as MovieListAdapter).setMovieList(movieList)
Adapter 에 무비 리스트를 넣어줄 때, MovieListModel 에서 필요한 value object 클래스를 만들어서 넣어주면 각각 아이템들이 가지는 데이터의 양이 적어져서 더 좋을 것 같습니다.

2020-03-10 11:06 UTC, Nanamare commented on ToyApplication/app/src/main/java/com/ironelder/toyapplication/NetworkService.kt
> +    fun getMovieList(@Path("type") type: String, @Query("page") page: Int? = 1, @Query("api_key") api_key: String = API_KEY): Call<MovieListModel>
여러 라인으로 분리가 되면 읽기 더욱 수월할 것 같습니다

2020-03-10 11:06 UTC, Nanamare commented on ToyApplication/app/src/main/java/com/ironelder/toyapplication/splash/SplashFragment.kt
> +        Handler().postDelayed({
(Optional ) 코루틴으로도 표현가능 할 것 같습니다?
ㅋ.ㅋ 개인의견입니당

2020-03-10 11:06 UTC, Nanamare commented on ToyApplication/app/src/main/java/com/ironelder/toyapplication/splash/SplashFragment.kt
> +            context?.let {
onViewCreated 에서
context?.let{
}
의 의미가 궁금합니다

2020-03-10 11:06 UTC, Nanamare commented on ToyApplication/app/src/main/java/com/ironelder/toyapplication/MovieListAdapter.kt
> +    fun setMovieList(list:List<MovieResultModel>){
Clear 필요하지 않나요 ?

2020-03-10 11:06 UTC, Nanamare commented on ToyApplication/app/src/main/java/com/ironelder/toyapplication/MovieListFragment.kt
> +                override fun onFailure(call: Call<MovieListModel>, t: Throwable) {
에러에 대한 처리도 있으면 좋을 것 같습니다

2020-03-10 11:06 UTC, Nanamare commented on ToyApplication/app/src/main/java/com/ironelder/toyapplication/NetworkServiceApi.kt
> +                .header("api_key", API_KEY)
get queryString 에 넣지 않고 헤더에 넣어도 동작하나요 ?.?(궁금합니당)
그렇게 Movie DB 에서 처리해주면 저도 비슷하게 가려고 합니다 ㅎㅎ
기본적으로 Http 메소드 Get 에서 Query 가 비이상적으로 길어지면 성능을 보장할 수 없다고 알고 있습니다.

2020-03-10 11:06 UTC, Nanamare commented on ToyApplication/app/src/main/java/com/ironelder/toyapplication/model/movielist/MovieListModel.kt
> +)
pagination 처리가 되어 있나요?

2020-03-10 11:06 UTC, Nanamare commented on ToyApplication/app/src/main/java/com/ironelder/toyapplication/MovieListFragment.kt
> +                    if (response.body()?.movieResultModels != null) {
좀더 코틀린스럽게 짤 수 있을 것 같습니다

2020-03-10 11:06 UTC, Nanamare commented on ToyApplication/app/src/main/java/com/ironelder/toyapplication/MovieListFragment.kt
> +        (rv_movie_list.layoutManager as GridLayoutManager).spanSizeLookup = object : GridLayoutManager.SpanSizeLookup(){
좀더 코틀린스럽게 변경시킬 수 있을 것 같습니다
GridLayoutManager(context, 6).apply {} 등등

2020-03-10 11:26 UTC, Nanamare requested changes

2020-03-10 11:26 UTC, Nanamare commented on ToyApplication/app/src/main/java/com/ironelder/toyapplication/MovieListFragment.kt
> +    override fun onActivityCreated(savedInstanceState: Bundle?) {
onActivityCreated(Deprecated 예정) 대신 onViewCreated 를 사용하도록 구글에서 추천하고 있습니다

2020-03-10 11:26 UTC, Nanamare commented on ToyApplication/app/src/main/java/com/ironelder/toyapplication/MovieListFragment.kt
> +                        (rv_movie_list.adapter as MovieListAdapter).setMovieList(movieList)
MovieListAdapter 를 프로퍼티에서 by lazy 하게 정의해서 쓰면 이런 캐스팅은 필요 없지 않나요 ?
위의  rv_movie_list.adapter = MovieListAdapter()  도 적용할 수 있을 것 같습니다

2020-03-10 11:26 UTC, Nanamare commented on ToyApplication/app/src/main/java/com/ironelder/toyapplication/MovieListFragment.kt
> +        completableJob.cancel()
액티비티 파괴될 때, onDestroy 안타는 경우도 존재해서 onStop 같은 곳에서 cancel 하는 것을 권장했던 것 같습니다

2020-03-10 11:26 UTC, Nanamare commented on ToyApplication/app/src/main/java/com/ironelder/toyapplication/NetworkServiceApi.kt
> +    val imageServiceApi: NetworkService by lazy {
필요없지 않나용 ?

2020-03-10 11:26 UTC, Nanamare commented on ToyApplication/app/src/main/java/com/ironelder/toyapplication/model/movielist/MovieResultModel.kt
> +data class MovieResultModel(
코틀린의 컨벤션에서 기본 camel 케이스를 권장 합니다

2020-03-10 11:26 UTC, Nanamare commented on Navigation/app/build.gradle
> +    implementation 'androidx.appcompat:appcompat:1.0.2'
버전은 따로 관리해도 괜찮을 것 같습니다

2020-03-12 09:06 UTC, zion830 commented on ToyApplication/app/src/main/java/com/ironelder/toyapplication/MovieListFragment.kt
> +            poster_path = IMAGE_BASE_URL + it.poster_path,
여기서 map이 쓰이는 것은 포스터 이미지 때문인가요?!
이미지 URL이 실제로 필요한 단계에서 IMAGE_BASE_URL를 붙여주면 모든 프로퍼티를 mapping 하지 않아도 될 것 같아요.

2020-03-12 09:28 UTC, zion830 commented on ToyApplication/app/src/main/java/com/ironelder/toyapplication/model/movielist/MovieResultModel.kt
> +data class MovieResultModel(
이 부분은 혹시 서버에서 떨어지는 json key 네이밍에 맞춰 쓰신거면..?
SerializedName라는 어노테이션으로 대체하면 좋을 것 같습니다.

2024-08-12 10:01 UTC, closed without merging