영화 목록 조회 앱 구현하기
StudyFork/CleanArchitectureStudy02 pull request #26
Opened 2020-03-11 14:12 UTC by zion830

코루틴으로 api call 하는 기본적인 작업만 해뒀고 조금씩 리팩토링 할 예정입니다.

### 스크린샷
<img src="https://blogfiles.pstatic.net/MjAyMDAzMTFfMjEx/MDAxNTgzOTM1ODE5MjE4.01utrgT4rPon4oiS4pfwH9L3rdvZHMMO2BQlTmz2apQg.gbgELi3KMQu58C6j95-YNw-kusLBO6LCbCV3UdqJITgg.PNG.zion830/%EC%8A%A4%ED%81%AC%EB%A6%B0%EC%83%B7_2020-03-11_%EC%98%A4%ED%9B%84_11.09.48.png?type=w1" width=300 />

2020-03-12 15:13 UTC, Nanamare requested changes

2020-03-12 15:13 UTC, Nanamare commented on CleanArchitectureStudy/app/src/main/java/yunji/cleanarchitecturestudy02/base/BaseBindingAdapter.kt
> +    (rv.adapter as BaseRecyclerView<*, Any>).updateItems(data ?: listOf())
listOf() 에서 내부적으로 emptyListOf() 를 호출하기 때문에 명시적으로 emptyListOf 를 주셔도 좋을 것 같습니다

2020-03-12 15:13 UTC, Nanamare commented on CleanArchitectureStudy/app/src/main/java/yunji/cleanarchitecturestudy02/base/BaseBindingAdapter.kt
> +    view.setPadding(view.paddingLeft, padding, view.paddingRight, padding)
요런식으로 써도 되는데, 명시적으로 받으시는건가요 ? 다른 BindingAdapter 들도용!
fun View.setPaddingVertical(padding: Int) {
    setPadding(paddingLeft, padding, paddingRight, padding)
}

2020-03-12 15:13 UTC, Nanamare commented on CleanArchitectureStudy/app/src/main/java/yunji/cleanarchitecturestudy02/base/BaseRecyclerView.kt
> +    var onItemClickListener = object : OnItemClickListener<T> {
<img width="235" alt="스크린샷 2020-03-12 오후 10 24 10" src="https://user-images.githubusercontent.com/17498974/76531259-4a357980-64b8-11ea-832e-175d4c04529a.png">
<img width="364" alt="스크린샷 2020-03-12 오후 10 24 00" src="https://user-images.githubusercontent.com/17498974/76531266-4c97d380-64b8-11ea-9024-1bd97a7d6cd0.png">

인터페이스가 언어차원에서 제공해주는 것이 있습니다. 현재 min 24에서 지원해주는데, 
앞으로는 api level 이 올라갈꺼니까 제공해주는 클래스로 변경해보는 것도 좋을 것 같습니다.
자바는 함수가 일급 취급 받지 못해서 저렇게 함수형 인터페이스로 제공해주는 클래스들이 다양한데, 이 부분에 대해 공부하셔도 좋을 것 같습니다.

e.g) 
abstract class OnSingleClickListener<T>(
    private val clickDelayMilliSeconds: Long = CLICK_DELAY_TIME
) : Consumer<T> {
    private var lastClickTime = 0L

    override fun accept(item: T) {
        val now = System.currentTimeMillis()
        if ((now - lastClickTime) > clickDelayMilliSeconds) { // 중복 클릭 방지
            onSingleClick(item)
            lastClickTime = now
        }
    }

    abstract fun onSingleClick(item: T)

    companion object {
        private const val CLICK_DELAY_TIME = 500L

        fun <T> wrap(
            listener: Consumer<T>,
            clickDelayMilliSeconds: Long = CLICK_DELAY_TIME
        ): Consumer<T> {
            return object : OnSingleClickListener<T>(clickDelayMilliSeconds),
                Consumer<T> {
                override fun onSingleClick(item: T) {
                    listener.accept(item)
                }
            }
        }
    }
}

2020-03-12 15:13 UTC, Nanamare commented on CleanArchitectureStudy/app/src/main/java/yunji/cleanarchitecturestudy02/base/BaseRecyclerView.kt
> +    var onItemClickListener = object : OnItemClickListener<T> {
java 패키지에도 있고 android.x 패키지에서도 제공해줍니다.
그리고 제공된 함수인터페이스를 사용하는 것을 권장합니다

2020-03-12 15:13 UTC, Nanamare commented on CleanArchitectureStudy/app/src/main/java/yunji/cleanarchitecturestudy02/base/BaseViewHolder.kt
> +abstract class BaseViewHolder<out B : ViewDataBinding, T>(
여기 뷰데이터바인딩에 공변성 주는건 의도하신건가요?

2020-03-12 15:13 UTC, Nanamare commented on CleanArchitectureStudy/app/src/main/java/yunji/cleanarchitecturestudy02/listener/OnSingleClickListener.kt
> +abstract class OnSingleClickListener<T>(
요런 로직은 Rx 사용하게되면 엄청나게 간단하게 줄어들 것 같네요
물론 굳이 하실필요는 없습니다 ㅋ.ㅋ

2020-03-12 15:13 UTC, Nanamare commented on CleanArchitectureStudy/app/src/main/java/yunji/cleanarchitecturestudy02/model/response/Movie.kt
> +    override fun hashCode(): Int {
자바에서는 소수로 hashCode 를 구현하는 방법은 일반적인데, 코틀린의 데이터 클래스는 기본적으로 가지고 있는 모든 프로퍼티를 사용하여 Canonical  method(equals, hashCode, toString) 들을 만들어 내기 때문에 괜찮지 않나요 ?
의도가 궁금합니다.

2020-03-12 15:13 UTC, Nanamare commented on CleanArchitectureStudy/app/src/main/java/yunji/cleanarchitecturestudy02/model/response/MovieDetailsResponse.kt
> +    val belongsToCollection: Any,
Any 로 들어왔는데 어떤 타입인지 궁금하네요 
그냥 궁금증입니다

2020-03-12 15:13 UTC, Nanamare commented on CleanArchitectureStudy/app/src/main/java/yunji/cleanarchitecturestudy02/viewmodel/MainViewModel.kt
> +    private val _movieList = MutableLiveData<List<Movie>>()
Movie가 서버에서 받아온 data  class 인데, 받아온 데이터 자체를 UI 로 보여주는 구조는 앱의 다른 화면이나 등등 재사용할 수가 없어서 안티 패턴이라고 책에서 읽은 적이 있습니다. 그 책에서는 UI 에 보여주는 값만 가지고 있는 객체 MovieVO 를 만들어 처리해라 라고 봤던 것 같네요

2020-03-12 15:13 UTC, Nanamare commented on CleanArchitectureStudy/app/src/main/java/yunji/cleanarchitecturestudy02/viewmodel/MainViewModel.kt
> +    val movieList: LiveData<List<Movie>>
저는 이렇게 _ prefix 붙여서 get set 제한하는게 습관이 안되더라구요..

2020-03-12 15:13 UTC, Nanamare commented on CleanArchitectureStudy/app/src/main/java/yunji/cleanarchitecturestudy02/viewmodel/MainViewModel.kt
> +        _movieList.value = listOf()
private val _movieList = MutableLiveData<List<Movie>>().apply { 
        value = emptyList()
}
로 init 블록을 줄일 수 있을 것 같습니다

보통 init 블록은 생성자를 통해서나, 프로퍼티 초기화등으로 해결될 수 없는 상황에서 사용되는 것으로 알고 있습니다. (아주 어려운 알고리즘을 작성 등)

2020-03-12 15:13 UTC, Nanamare commented on CleanArchitectureStudy/app/src/main/java/yunji/cleanarchitecturestudy02/viewmodel/MainViewModel.kt
> +        repository.getPopularMovieList(page, success = {
```
repository.getPopularMovieList(page,
            success = {
                totalPages = it.totalPages
                _movieList.value = _movieList.value?.plus(it.movies)
                _isLoading.value = false
            },
            failed = {
                _msgText.value = it
                _isLoading.value = false
            })

```
저는 이런식으로 작성하는 편입니다(개인적인 의견)

2020-03-12 15:13 UTC, Nanamare commented on CleanArchitectureStudy/app/src/main/java/yunji/cleanarchitecturestudy02/viewmodel/MainViewModelFactory.kt
> +    override fun <T : ViewModel?> create(modelClass: Class<T>): T = MainViewModel(movieRepository) as T
```
override fun <T : ViewModel> 
```
해도 상관 없을 것 같습니다

2020-03-13 11:10 UTC, zion830 reviewed
자세한 리뷰 감사합니다!
무한스크롤을 리뷰 해주신 이후에 넣어서 여기저기 바뀐 부분이 많습니다 ㅠㅠ

2020-03-13 11:10 UTC, zion830 commented on CleanArchitectureStudy/app/src/main/java/yunji/cleanarchitecturestudy02/base/BaseBindingAdapter.kt
> +    (rv.adapter as BaseRecyclerView<*, Any>).updateItems(data ?: listOf())
empthList로 변경했습니다

2020-03-13 11:10 UTC, zion830 commented on CleanArchitectureStudy/app/src/main/java/yunji/cleanarchitecturestudy02/base/BaseBindingAdapter.kt
> +    view.setPadding(view.paddingLeft, padding, view.paddingRight, padding)
요런 View와 관련된 부분은 코틀린 코드 대신 xml에서 지정하기 위해 bindingAdapter를 사용했습니다.

2020-03-13 11:10 UTC, zion830 commented on CleanArchitectureStudy/app/src/main/java/yunji/cleanarchitecturestudy02/base/BaseRecyclerView.kt
> +    var onItemClickListener = object : OnItemClickListener<T> {
똑같은 형태의 인터페이스가 내장되어있었군요~
지금은 min api가 21로 되어있어서 Consumer 클래스를 사용했더니 오류가 뜨네요 ㅠㅠ
함수형 인터페이스도 공부해 보도록 하겠습니다 알려주셔서 감사해요

2020-03-13 11:10 UTC, zion830 commented on CleanArchitectureStudy/app/src/main/java/yunji/cleanarchitecturestudy02/listener/OnSingleClickListener.kt
> +abstract class OnSingleClickListener<T>(
RxBinding을 사용하면 간편하게 처리할 수 있는 것으로 알고 있는데요,
아직 RxJava에 익숙하지 않아서 다중 클릭만 보고 새로운 라이브러리를 넣는건 좀 그런 것 같아서..😌
복잡한 로직은 아닌지라 직접 구현했습니다 ㅎㅎ

2020-03-13 11:10 UTC, zion830 commented on CleanArchitectureStudy/app/src/main/java/yunji/cleanarchitecturestudy02/model/response/MovieDetailsResponse.kt
> +    val belongsToCollection: Any,
이건 api 문서에 null or object 라고 타입이 명시되어있어서 Any로 선언해두었습니다. [링크](https://developers.themoviedb.org/3/movies/get-movie-details) 
리뷰해주셔서 다시 확인해보니 null도 들어갈 수 있을 것 같아서 Any?로 수정했어용

2020-03-13 11:10 UTC, zion830 commented on CleanArchitectureStudy/app/src/main/java/yunji/cleanarchitecturestudy02/base/BaseViewHolder.kt
> +abstract class BaseViewHolder<out B : ViewDataBinding, T>(
이건 out을 붙이면 자식 타입 클래스를 할당하는게 허용 된다고해서 넣었던 키워드인데요,
물론 val holder: BaseViewHolder<ViewDataBinding, Movie> = MovieViewHolder() 이런식으로 쓸 일이 없을 듯 해서 없어도 무방할거 같긴 합니다

2020-03-13 11:11 UTC, zion830 commented on CleanArchitectureStudy/app/src/main/java/yunji/cleanarchitecturestudy02/viewmodel/MainViewModelFactory.kt
> +    override fun <T : ViewModel?> create(modelClass: Class<T>): T = MainViewModel(movieRepository) as T
말씀 주신대로 바꿨습니다!

2020-03-13 11:12 UTC, zion830 commented on CleanArchitectureStudy/app/src/main/java/yunji/cleanarchitecturestudy02/viewmodel/MainViewModel.kt
> +        repository.getPopularMovieList(page, success = {
제안해주신 방법이 더 가독성이 좋은 것 같아서 바꿨습니다 ㅎㅎ

2020-03-13 11:12 UTC, zion830 commented on CleanArchitectureStudy/app/src/main/java/yunji/cleanarchitecturestudy02/viewmodel/MainViewModel.kt
> +    val movieList: LiveData<List<Movie>>
똑같은걸 두번 선언하는게 좀 번거롭기는 한데, 처음에 이렇게 배웠어서(?) 습관적으로 계속 이렇게 하고 있습니다 ㅎㅎ

2020-03-13 11:15 UTC, zion830 commented on CleanArchitectureStudy/app/src/main/java/yunji/cleanarchitecturestudy02/viewmodel/MainViewModel.kt
> +        _movieList.value = listOf()
이런식으로 수정했습니다
```
lateinit var pagingMovieList: LiveData<PagedList<Movie>>
...
fun initMovieData() {
    // pagingMovieList 초기화
...
```

2020-03-13 11:15 UTC, Nanamare commented on CleanArchitectureStudy/app/src/main/java/yunji/cleanarchitecturestudy02/base/BaseBindingAdapter.kt
> +    view.setPadding(view.paddingLeft, padding, view.paddingRight, padding)
@BindingAdapter("setPaddingVertical")
fun View.setPaddingVertical(padding: Int) {
    setPadding(paddingLeft, padding, paddingRight, padding)
}

요렇게 쓰면 view 생략할 수있지 않나용

2020-03-13 11:18 UTC, Nanamare commented on CleanArchitectureStudy/app/src/main/java/yunji/cleanarchitecturestudy02/base/BaseViewHolder.kt
> +abstract class BaseViewHolder<out B : ViewDataBinding, T>(
네 설명해주신 나와 내 자식 타입을 할당할 수 있는 것을 공변성이라고 합니다 ㅋ.ㅋ
말고도 반공변(나와 나 부모 타입 할당만 허용), 무공변(내 타입만 허용)이 있습니다

2020-03-13 11:20 UTC, zion830 commented on CleanArchitectureStudy/app/src/main/java/yunji/cleanarchitecturestudy02/model/response/Movie.kt
> +    override fun hashCode(): Int {
디폴트로 구현되는 equals는 모든 프로퍼티를 비교하는 걸로 알고있는데,
여기선 movie id가 유니크한 값이라는 암묵적인 합의(?)가 있다 생각하고 id를 기준으로 동일한 아이템인지 판단하려고 재정의를 했습니다. equals가 바뀌어서 hashCode도 같이 재정의했구요.

그런데 더 생각해보니 영화 자체의 id는 동일하지만 세부 정보가 바뀌는 상황도 있을 것 같아서, 오버라이딩한 equals & hashCode는 삭제하고 [이렇게](https://github.com/StudyFork/CleanArchitectureStudy02/blob/bc7db79dd2052763eb848ec765a3e3f7ca755cdf/CleanArchitectureStudy/app/src/main/java/yunji/cleanarchitecturestudy02/adapter/MoviePagedRecyclerAdapter.kt) BaseDiffUtilCallback를 직접 재정의하는 방식으로 수정했습니다.

2020-03-13 11:22 UTC, Nanamare commented on CleanArchitectureStudy/app/src/main/java/yunji/cleanarchitecturestudy02/base/BaseRecyclerView.kt
> +    var onItemClickListener = object : OnItemClickListener<T> {
Level 이 올라감에 따라, 앞으로 자주 마주?하게 될 꺼 같습니다 ㅋ.ㅋ
넘기는 파라미터가 2개일때 3개일때 인트일때 등등 되게 많이 제공해줍니다

2020-03-13 11:30 UTC, zion830 commented on CleanArchitectureStudy/app/src/main/java/yunji/cleanarchitecturestudy02/viewmodel/MainViewModel.kt
> +    private val _movieList = MutableLiveData<List<Movie>>()
Movie가 서로 다르게 사용되는 횟수 만큼 대응되는 MovieVO들을 만든다는 건가용? 재사용 가능하게 만드는게 어떤 의미인지 약간 짐작이 안되네요 ㅜ

2020-03-13 11:35 UTC, zion830 commented on CleanArchitectureStudy/app/src/main/java/yunji/cleanarchitecturestudy02/base/BaseBindingAdapter.kt
> +    view.setPadding(view.paddingLeft, padding, view.paddingRight, padding)
아 그런 의미였군요~ 확장함수 쓰도록 바꿨습니다 ㅎㅎ
fe61736

2020-03-13 11:38 UTC, Nanamare commented on CleanArchitectureStudy/app/src/main/java/yunji/cleanarchitecturestudy02/viewmodel/MainViewModel.kt
> +    private val _movieList = MutableLiveData<List<Movie>>()
위에서 보여주는 UI 에서는 영화 제목, 내용, 개봉 일자 만 보여주는데, Movie 에는 더 많은 정보들이 들어있으니, 다른 로직에서 이런 정보를  필요로 한다면 따로 가지고 있고, 필요 없다면 버려도 될 것 같습니다. 그럼 메모리 공간도 조금 차지하겠고, 혹여나 다른 사람이 로직을 유지보수하면 정보의 양이 줄어 가독성있게 코딩을 할 수 있을 것 같습니다. 관심사를 분리한다고 생각하면 좋을 것 같습니다

2020-04-04 13:18 UTC, merged