영화 과제 추가
StudyFork/CleanArchitectureStudy02 pull request #28
Opened 2020-03-12 11:32 UTC by Nanamare

<img width="260" alt="스크린샷 2020-03-10 오후 8 45 22" src="https://user-images.githubusercontent.com/17498974/76516983-c8d1ed00-649f-11ea-9a54-1088bba44047.png">
<img width="258" alt="스크린샷 2020-03-10 오후 8 41 37" src="https://user-images.githubusercontent.com/17498974/76516997-d25b5500-649f-11ea-8dfd-56c597186c3a.png">

추천, 검색 기능 정도만 있습니다.
코루틴으로 바꾸려다가, RxBinding 사용해서 하나의 옵저버블로 쭉 처리해볼지 고민중에 있습니다.
피드백 부탁드립니다.

2020-03-12 12:25 UTC, zion830 commented
오 장르별로 분류까지..!
디자인도 엄청 이쁘게 해두셨네요.. 역시 현성님..😲
시간 되는대로 리뷰 남기도록 하겠습니다

2020-03-13 17:46 UTC, zion830 requested changes
리뷰 남겨봤습니다!
구현해두신 기능도 많고 역시 잘 하셔서 보는것만으로 공부가 많이 되었습니다 😆

2020-03-13 17:46 UTC, zion830 commented on ToyProject/app/src/main/java/com/template/nanamare/utils/Logger.kt
> +    private val BUILD_TYPE = "debug"
상수면 const val로 선언하면 좋을거 같습니다~
그런데 이 변수는 AppApplication에도 정의되어 있는 것 같은데 서로 다른 사용처가 있는건가요?

2020-03-13 17:46 UTC, zion830 commented on ToyProject/app/src/main/java/com/template/nanamare/base/ui/BaseActivity.kt
> +abstract class BaseActivity<B : ViewDataBinding>(private val layoutId: Int) : AppCompatActivity(),
혹시 모를 실수를 예방하는 차원에서 리소스 아이디엔 @LayoutRes 같은 어노테이션을 붙이면 좋을 것 같습니다!

2020-03-13 17:46 UTC, zion830 commented on ToyProject/app/src/main/java/com/template/nanamare/ui/fragment/MovieFragment.kt
> +class MovieFragment(private val genres: List<GenreResponse.Genre>) :
요기서 기본 생성자를 사용하는게 좋을 것 같습니다.
안드로이드 시스템이 프레그먼트를 복원시킬 때 프래그먼트의 기본 생성자를 호출하기 때문에, 생성자로 넘기는 데이터가 보장되지 않을 수 있다구 합니다.
아래는 참고한 fragment 문서 윗부분 입니다 ㅎㅎ
> All subclasses of Fragment must include a public no-argument constructor. The framework will often re-instantiate a fragment class when needed, in particular during state restore, and needs to be able to find this constructor to instantiate it. If the no-argument constructor is not available, a runtime exception will occur in some cases during state restore.

2020-03-13 17:46 UTC, zion830 commented on ToyProject/app/src/main/java/com/template/nanamare/base/ui/BaseActivity.kt
> +        val layout = layoutInflater.inflate(R.layout.custom_toast, binding.root as ViewGroup, false)
단순한 UI라 큰 문제는 아니지만.. showToast를 사용할 때마다 레이아웃이 재구성 되는데요
한번만 초기화 할 수 있다면 좋지 않을까 하는 생각입니다!

2020-03-13 17:46 UTC, zion830 commented on ToyProject/app/src/main/java/com/template/nanamare/base/ui/BaseExceptionHandler.kt
> +        exitProcess(-1)
이미 killProcess가 위에 있어서 exitProcess는 호출될 일이 없지 않을까요..?

2020-03-13 17:46 UTC, zion830 commented on ToyProject/app/src/main/java/com/template/nanamare/base/ui/BaseRecyclerViewAdapter.kt
> +        items.clear()
이 다음에 notifyDataSetChanged()가 필요할 거 같습니당

2020-03-13 17:46 UTC, zion830 commented on ToyProject/app/src/main/java/com/template/nanamare/ui/fragment/MovieCategoryFragment.kt
> +                return object : BaseViewHolder<MovieResponse.Result, ItemMovieBinding>(
adapter를 초기화 하는 곳에서 ViewHolder까지 정의하고 있어서 뭔가 많은 일이 일어나는 느낌인데요,
이부분은 Fragment 바깥쪽으로 아예 분리하는 것도 나쁘지 않을 것 같습니당

2020-03-13 17:46 UTC, zion830 commented on ToyProject/app/src/main/java/com/template/nanamare/ui/fragment/MovieCategoryFragment.kt
> +                                vm = Movie(item.title, item.releaseDate, item.posterPath)
let으로 묶어놨기 때문에 item -> it으로 대체 가능할 것 같습니다ㅎㅎ

2020-03-13 17:46 UTC, zion830 commented on ToyProject/app/src/main/java/com/template/nanamare/base/ui/BaseRecyclerViewAdapter.kt
> +abstract class BaseRecyclerViewAdapter<ITEM : Any>
onCreateViewHolder는 없어도 괜찮나요 😯?

2020-03-13 17:46 UTC, zion830 commented on ToyProject/app/src/main/java/com/template/nanamare/base/ui/SimpleRecyclerView.kt
> +abstract class SimpleRecyclerView {
Q. Base 클래스랑 비슷한 역할을 하는 것 같은데 이렇게 따로 만들어두신 이유가 궁금합니다!

2020-03-13 17:46 UTC, zion830 commented on ToyProject/app/src/main/java/com/template/nanamare/data/repository/GenreRepository.kt
> +class GenreRepository(private val genreRemoteDataSourceImplImpl: GenreRemoteDataSourceImpl) :
변수명에 Impl이 두번 들어갔어요 ㅎㅎ

2020-03-13 17:46 UTC, zion830 commented on ToyProject/app/src/main/java/com/template/nanamare/data/source/MoviePagingDataSourceFactory.kt
> +    private val movieDataSource: com.template.nanamare.data.source.impl.MovieDataSource,
패키지 경로는 지워도 될거같아요~!

2020-03-13 17:46 UTC, zion830 commented on ToyProject/app/src/main/java/com/template/nanamare/data/source/MovieRemoteDataSourceImpl.kt
> +                            failed(converterErrorBody(it.string()))
subscribe 안의 람다랑, let 블록이 둘다 `it`을 사용하고 있어서 여기 it.string()이 어떤 scope의 value를 의미하는건지 혼동을 줄 수 있을 거 같아요. `subscribe({ response -> ...` 이런식으로 바꿔도 좋을 거 같습니다

2020-03-13 17:46 UTC, zion830 commented on ToyProject/app/src/main/java/com/template/nanamare/network/api/MovieAPI.kt
> +        @Query("api_key") secretKey: String = BuildConfig.SECRET_KEY,
사용할 api가 늘어날 경우를 고려하면 interceptor를 사용하는 것도 좋을 것 같습니다~

2020-03-13 17:46 UTC, zion830 commented on ToyProject/app/src/main/java/com/template/nanamare/ui/fragment/MovieCategoryFragment.kt
> +            ): Boolean =
View와 직접적인 연관이 있는 로직이 아니라서 여기에 ItemCallback이 있는게 약간은 어색한 느낌인데요
Fragment 내부에 두는 것보다 Adapter 등 다른 곳으로 옮기는건 어떨까요?

2020-03-13 17:46 UTC, zion830 commented on ToyProject/app/src/main/java/com/template/nanamare/vm/MainViewModel.kt
> +                                NetworkState.serverError(converterErrorBody(it.string()))
여기도 위와 마찬가지로 it을 사용하는 블록이 중첩되어 있어서 헷갈릴 수 있을 것 같습니다 ㅎㅎ

2020-03-13 17:46 UTC, zion830 commented on ToyProject/app/src/main/java/com/template/nanamare/vm/MovieCategoryViewModel.kt
> +        MutableLiveData<LiveData<PagedList<MovieResponse.Result>>>()
여기서 MutableLiveData가 LiveData를 타입으로 가지는 이유가 궁금합니다!
setValue 없이 바로 LivePagedListBuilder로 초기화해도 되지 않나용?

2020-03-14 05:42 UTC, Nanamare commented on ToyProject/app/src/main/java/com/template/nanamare/utils/Logger.kt
> +    private val BUILD_TYPE = "debug"
원래는 Logger 를 만들때는 독립적인 모듈, 혹은 라이브러리로 만드려다가, 현재는 프로젝트에 들어있어서 필요가 없어졌네요.
현재는 Application 에 선언되어있는 것을 삭제하고 Logger object 에는 상수화 시켜놨습니다

2020-03-14 05:45 UTC, Nanamare commented on ToyProject/app/src/main/java/com/template/nanamare/utils/Logger.kt
> +    private val BUILD_TYPE = "debug"
1f067325711a3077161ca26ce412783af2cdf440

2020-03-14 05:47 UTC, Nanamare commented on ToyProject/app/src/main/java/com/template/nanamare/base/ui/BaseActivity.kt
> +abstract class BaseActivity<B : ViewDataBinding>(private val layoutId: Int) : AppCompatActivity(),
ecf702ff8f7e1ee1ec4d98d1952f98013135843d
적용하였습니당

2020-03-14 05:51 UTC, Nanamare commented on ToyProject/app/src/main/java/com/template/nanamare/ui/fragment/MovieFragment.kt
> +class MovieFragment(private val genres: List<GenreResponse.Genre>) :
말씀해주신 부분이 기존의 안드로이드 디자인이였는데, 비효율적이라고 구글에서 생각하여 현재는 fragmentFactory 를 권장하고 있습니다.

https://link.medium.com/JVqvfWwLP4 에 잘 설명되어있고, 저는 Koin 에서 제공해주는 KoinFragmentFactory 를 사용하고있습니다

내부 코드보면 빈생성자를 호출하는 부분을 FragmentFactory instantiate 메소드에서 해결하고 있습니다

```
/**
 * usage
 * setupKoinFragmentFactory() in activity before super.onCreate(savedInstanceState)
 */
val fragmentModule: Module = module {
    fragment { (movies: List<GenreResponse.Genre>) ->
        MovieFragment(movies)
    }
    fragment { (movie: GenreResponse.Genre) ->
        MovieCategoryFragment(movie)
    }
}
```

2020-03-14 05:53 UTC, Nanamare commented on ToyProject/app/src/main/java/com/template/nanamare/ui/fragment/MovieFragment.kt
> +class MovieFragment(private val genres: List<GenreResponse.Genre>) :
Android x 부터 권장되는 방식입니다.

2020-03-14 06:15 UTC, Nanamare commented on ToyProject/app/src/main/java/com/template/nanamare/base/ui/BaseActivity.kt
> +        val layout = layoutInflater.inflate(R.layout.custom_toast, binding.root as ViewGroup, false)
e7d01820a22c42ce29c88260471db64c24e9e6b9
요런식으로 처리하고, 다른 부분들도 같이 처리하고싶었는데, msg, error 아규먼트를 받아서 애매함이 있네요

2020-03-14 06:16 UTC, Nanamare commented on ToyProject/app/src/main/java/com/template/nanamare/base/ui/BaseRecyclerViewAdapter.kt
> +        items.clear()
사용하지 않는 클래스라서 삭제했습니다

2020-03-14 06:17 UTC, Nanamare commented on ToyProject/app/src/main/java/com/template/nanamare/base/ui/BaseRecyclerViewAdapter.kt
> +abstract class BaseRecyclerViewAdapter<ITEM : Any>
사용하지 않는 클래스라서 삭제했습니다

2020-03-14 06:26 UTC, Nanamare commented on ToyProject/app/src/main/java/com/template/nanamare/base/ui/BaseExceptionHandler.kt
> +        exitProcess(-1)
저도 이부분은 참고해서 확실하지는 않지만, killProcess 로 프로세스(현재 Activity) 제거하는데,
어떠한 이유로 인해 프로세서를 제거하지 못하면 강제적으로 제거하기위해 exitProcess 를 사용하는 것으로 알고 있습니다.
참고로 exitProcess 함수 내부에서 아래 함수를 호출하는데, -1 값을 넣을 때는 비정상적일 때 프로세스를 종료하기 위함이라고 하네요
System.exit(status)

2020-03-14 06:30 UTC, Nanamare commented on ToyProject/app/src/main/java/com/template/nanamare/base/ui/SimpleRecyclerView.kt
> +abstract class SimpleRecyclerView {
템플릿 프로젝트에 추가되어 있던 애들 긁어다가 사용하다 보니 필요없는 코드들이 좀 들어 간 것 같습니다.
몇번 걸렀는데도 남아있네요 ㅋ.ㅋ RecyclerView 관련 작업은 제가 Base 들을 많이 정의해두고, 상황에 맞게 골라서 사용해서 그런지 특히 이런 클래스들이 많은 것 같습니다

2020-03-14 06:30 UTC, Nanamare commented on ToyProject/app/src/main/java/com/template/nanamare/data/repository/GenreRepository.kt
> +class GenreRepository(private val genreRemoteDataSourceImplImpl: GenreRemoteDataSourceImpl) :
맙소사..

2020-03-14 07:22 UTC, Nanamare commented on ToyProject/app/src/main/java/com/template/nanamare/ui/fragment/MovieCategoryFragment.kt
> +                return object : BaseViewHolder<MovieResponse.Result, ItemMovieBinding>(
552a274ecfbdb700dc67db25ae99982228f9e380
분리했습니다

2020-03-14 07:23 UTC, Nanamare commented on ToyProject/app/src/main/java/com/template/nanamare/ui/fragment/MovieCategoryFragment.kt
> +                                vm = Movie(item.title, item.releaseDate, item.posterPath)
4e17ab1e92eb586e64648676185cc44b121a8efb
대체했습니다

2020-03-14 07:26 UTC, Nanamare commented on ToyProject/app/src/main/java/com/template/nanamare/data/source/MoviePagingDataSourceFactory.kt
> +    private val movieDataSource: com.template.nanamare.data.source.impl.MovieDataSource,
48ed9f3fe51403bdd488a70586d35904c39d2e1a

2020-03-14 07:31 UTC, Nanamare commented on ToyProject/app/src/main/java/com/template/nanamare/data/source/MovieRemoteDataSourceImpl.kt
> +                            failed(converterErrorBody(it.string()))
9947f25041ceba0ebaa268cf8655ad7777ae9a8e

2020-03-14 12:50 UTC, zion830 commented on ToyProject/app/src/main/java/com/template/nanamare/ui/fragment/MovieFragment.kt
> +class MovieFragment(private val genres: List<GenreResponse.Genre>) :
오호 이런게 있었군요??
새로 배워가네용

2020-03-14 13:50 UTC, Nanamare commented on ToyProject/app/src/main/java/com/template/nanamare/data/source/MovieRemoteDataSourceImpl.kt
> +                            failed(converterErrorBody(it.string()))
9947f25041ceba0ebaa268cf8655ad7777ae9a8e
잠시 외출다녀왔습니다 ㅎㅎ

2020-03-14 13:50 UTC, Nanamare commented on ToyProject/app/src/main/java/com/template/nanamare/network/api/MovieAPI.kt
> +        @Query("api_key") secretKey: String = BuildConfig.SECRET_KEY,
e2093f1622418bb3696d6f72e801a60df1717f87
오 이거 너무 좋습니다

2020-03-14 13:52 UTC, Nanamare commented on ToyProject/app/src/main/java/com/template/nanamare/ui/fragment/MovieCategoryFragment.kt
> +            ): Boolean =
Adapter 분리하면서 같이 옴겼습니다

2020-03-14 13:53 UTC, Nanamare commented on ToyProject/app/src/main/java/com/template/nanamare/vm/MainViewModel.kt
> +                                NetworkState.serverError(converterErrorBody(it.string()))
ec188ffa75bbbb09dc20f13faeca09a0016f4c8c

2020-03-14 14:08 UTC, Nanamare commented on ToyProject/app/src/main/java/com/template/nanamare/vm/MovieCategoryViewModel.kt
> +        MutableLiveData<LiveData<PagedList<MovieResponse.Result>>>()
이해가 될듯 되지 않아서, 혹시 코드로 가이드 해주실 수 있나요 ?

2020-03-14 16:23 UTC, zion830 commented on ToyProject/app/src/main/java/com/template/nanamare/vm/MovieCategoryViewModel.kt
> +        MutableLiveData<LiveData<PagedList<MovieResponse.Result>>>()
```
lateinit var liveMovies: LiveData<PagedList<MovieResponse.Result>>
...
fun requestDiscoverMovies(id: Int, requestMovieApiType: RequestMovieApiType) {
        baseNavigator.showLoadingPopup()
        liveMovies = LivePagedListBuilder(MoviePagingDataSourceFactory(
...
}).build()
```
이렇게 작성하는 방식을 얘기한 거였습니다 ㅎㅎ
그러면 MovieCategoryFragment 안에서 Observer가 중첩되지 않아도 될 것 같아서요.

2020-04-04 01:47 UTC, merged